/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarmupRouteImport } from './routes/warmup'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MoveMoneyRouteImport } from './routes/move-money'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoveMoneyTransferRouteImport } from './routes/move-money/transfer'
import { Route as AccountsIndexAccountIdRouteImport } from './routes/accounts/index.$accountId'

const WarmupRoute = WarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveMoneyRoute = MoveMoneyRouteImport.update({
  id: '/move-money',
  path: '/move-money',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveMoneyTransferRoute = MoveMoneyTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => MoveMoneyRoute,
} as any)
const AccountsIndexAccountIdRoute = AccountsIndexAccountIdRouteImport.update({
  id: '/accounts/index/$accountId',
  path: '/accounts/index/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/move-money': typeof MoveMoneyRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/warmup': typeof WarmupRoute
  '/move-money/transfer': typeof MoveMoneyTransferRoute
  '/accounts/index/$accountId': typeof AccountsIndexAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/move-money': typeof MoveMoneyRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/warmup': typeof WarmupRoute
  '/move-money/transfer': typeof MoveMoneyTransferRoute
  '/accounts/index/$accountId': typeof AccountsIndexAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/move-money': typeof MoveMoneyRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/warmup': typeof WarmupRoute
  '/move-money/transfer': typeof MoveMoneyTransferRoute
  '/accounts/index/$accountId': typeof AccountsIndexAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/move-money'
    | '/profile'
    | '/rewards'
    | '/warmup'
    | '/move-money/transfer'
    | '/accounts/index/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/move-money'
    | '/profile'
    | '/rewards'
    | '/warmup'
    | '/move-money/transfer'
    | '/accounts/index/$accountId'
  id:
    | '__root__'
    | '/'
    | '/move-money'
    | '/profile'
    | '/rewards'
    | '/warmup'
    | '/move-money/transfer'
    | '/accounts/index/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoveMoneyRoute: typeof MoveMoneyRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  WarmupRoute: typeof WarmupRoute
  AccountsIndexAccountIdRoute: typeof AccountsIndexAccountIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warmup': {
      id: '/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof WarmupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move-money': {
      id: '/move-money'
      path: '/move-money'
      fullPath: '/move-money'
      preLoaderRoute: typeof MoveMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move-money/transfer': {
      id: '/move-money/transfer'
      path: '/transfer'
      fullPath: '/move-money/transfer'
      preLoaderRoute: typeof MoveMoneyTransferRouteImport
      parentRoute: typeof MoveMoneyRoute
    }
    '/accounts/index/$accountId': {
      id: '/accounts/index/$accountId'
      path: '/accounts/index/$accountId'
      fullPath: '/accounts/index/$accountId'
      preLoaderRoute: typeof AccountsIndexAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MoveMoneyRouteChildren {
  MoveMoneyTransferRoute: typeof MoveMoneyTransferRoute
}

const MoveMoneyRouteChildren: MoveMoneyRouteChildren = {
  MoveMoneyTransferRoute: MoveMoneyTransferRoute,
}

const MoveMoneyRouteWithChildren = MoveMoneyRoute._addFileChildren(
  MoveMoneyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoveMoneyRoute: MoveMoneyRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  WarmupRoute: WarmupRoute,
  AccountsIndexAccountIdRoute: AccountsIndexAccountIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
