/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WarmupImport } from './routes/warmup'
import { Route as RewardsImport } from './routes/rewards'
import { Route as ProfileImport } from './routes/profile'
import { Route as MoveMoneyImport } from './routes/move-money'
import { Route as IndexImport } from './routes/index'
import { Route as AccountsIndexAccountIdImport } from './routes/accounts/index.$accountId'

// Create/Update Routes

const WarmupRoute = WarmupImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => rootRoute,
} as any)

const RewardsRoute = RewardsImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const MoveMoneyRoute = MoveMoneyImport.update({
  id: '/move-money',
  path: '/move-money',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AccountsIndexAccountIdRoute = AccountsIndexAccountIdImport.update({
  id: '/accounts/index/$accountId',
  path: '/accounts/index/$accountId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/move-money': {
      id: '/move-money'
      path: '/move-money'
      fullPath: '/move-money'
      preLoaderRoute: typeof MoveMoneyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsImport
      parentRoute: typeof rootRoute
    }
    '/warmup': {
      id: '/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof WarmupImport
      parentRoute: typeof rootRoute
    }
    '/accounts/index/$accountId': {
      id: '/accounts/index/$accountId'
      path: '/accounts/index/$accountId'
      fullPath: '/accounts/index/$accountId'
      preLoaderRoute: typeof AccountsIndexAccountIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/move-money': typeof MoveMoneyRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/warmup': typeof WarmupRoute
  '/accounts/index/$accountId': typeof AccountsIndexAccountIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/move-money': typeof MoveMoneyRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/warmup': typeof WarmupRoute
  '/accounts/index/$accountId': typeof AccountsIndexAccountIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/move-money': typeof MoveMoneyRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/warmup': typeof WarmupRoute
  '/accounts/index/$accountId': typeof AccountsIndexAccountIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/move-money'
    | '/profile'
    | '/rewards'
    | '/warmup'
    | '/accounts/index/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/move-money'
    | '/profile'
    | '/rewards'
    | '/warmup'
    | '/accounts/index/$accountId'
  id:
    | '__root__'
    | '/'
    | '/move-money'
    | '/profile'
    | '/rewards'
    | '/warmup'
    | '/accounts/index/$accountId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoveMoneyRoute: typeof MoveMoneyRoute
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  WarmupRoute: typeof WarmupRoute
  AccountsIndexAccountIdRoute: typeof AccountsIndexAccountIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoveMoneyRoute: MoveMoneyRoute,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  WarmupRoute: WarmupRoute,
  AccountsIndexAccountIdRoute: AccountsIndexAccountIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/move-money",
        "/profile",
        "/rewards",
        "/warmup",
        "/accounts/index/$accountId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/move-money": {
      "filePath": "move-money.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/rewards": {
      "filePath": "rewards.tsx"
    },
    "/warmup": {
      "filePath": "warmup.tsx"
    },
    "/accounts/index/$accountId": {
      "filePath": "accounts/index.$accountId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
